# Generated by Django 5.1 on 2024-12-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('category_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewel_name', models.CharField(max_length=50)),
                ('jewel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jewel_description', models.TextField()),
                ('jewel_image', models.ImageField(upload_to='images/')),
                ('jewel_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewels', to='store.category')),
            ],
        ),
    ]
