# Generated by Django 5.1 on 2025-01-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_jewels_jewel_description_jewels_jewel_origin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
