# Generated by Django 5.1 on 2025-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_jewels_jewel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewels',
            name='jewel_image',
            field=models.ImageField(upload_to='jewellery_images/'),
        ),
    ]
