# Generated by Django 5.1 on 2025-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_jewels_jewel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewels',
            name='jewel_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
