# Generated by Django 5.1 on 2025-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_jewels_jewel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewels',
            name='jewel_image',
        ),
        migrations.AddField(
            model_name='jewels',
            name='jewel_image_url',
            field=models.URLField(null=True),
        ),
    ]
